export const PIN_DETAIL_GET_SUCCESS = "PIN_DETAIL_GET_SUCCESS"
export const PIN_DETAIL_GET_FAIL = "PIN_DETAIL_GET_FAIL"

export const FEED_PINS_GET_SUCCESS = "FEED_PINS_GET_SUCCESS"
export const FEED_PINS_GET_FAIL = "FEED_PINS_GET_FAIL"

export const MORE_PINS_GET_SUCCESS = "MORE_PINS_GET_SUCCESS"
export const MORE_PINS_GET_FAIL = "MORE_PINS_GET_FAIL"

export const SEARCH_PINS_GET_SUCCESS = "SEARCH_PINS_GET_SUCCESS"
export const SEARCH_PINS_GET_FAIL = "SEARCH_PINS_GET_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"