export const USER_GET_SUCCESS = "USER_GET_SUCCESS"

export const USER_GET_FAIL = "USER_GET_FAIL"

export const CURRENT_PROFILE_SET = "URRENT_PROFILE_SET"

export const GIFTING_USER_SET = "GIFTING_USER_SET"

export const HAS_MORE = "HAS_MORE"

export const CHANGE_PAGE = "CHANGE_PAGE"

export const REFRESH_SET = "REFRESH_SET"

export const COLLECTION_SET = "COLLECTION_SET"

export const MARKET_CONTRACT = "MARKET_CONTRACT"

export const CLEAR_ERRORS = "CLEAR_ERRORS"