export const USER_GET_SUCCESS = "USER_GET_SUCCESS"
export const USER_GET_FAIL = "USER_GET_FAIL"

export const SEARCH_TERM_SET = "SEARCH_TERM_SET"

export const REFRESH_SET = "REFRESH_SET"

export const CLEAR_ERRORS = "CLEAR_ERRORS"