export const USER_GET_SUCCESS = "USER_GET_SUCCESS"
export const USER_GET_FAIL = "USER_GET_FAIL"

export const PROFILE_GET_SUCCESS = "PROFILE_GET_SUCCESS"
export const PROFILE_GET_FAIL = "PROFILE_GET_FAIL"

export const OTHER_USER_GET_SUCCESS = "OTHER_USER_GET_SUCCESS"
export const OTHER_USER_GET_FAIL = "OTHER_USER_GET_FAIL"

export const USER_SAVE_GET_SUCCESS = "USER_SAVE_GET_SUCCESS"
export const USER_SAVE_GET_FAIL = "USER_SAVE_GET_FAIL"

export const USER_OWN_GET_SUCCESS = "USER_OWN_GET_SUCCESS"
export const USER_OWN_GET_FAIL = "USER_OWN_GET_FAIL"

export const USER_SALE_GET_SUCCESS = "USER_SALE_GET_SUCCESS"
export const USER_SALE_GET_FAIL = "USER_SALE_GET_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"